### ISSUE TITLE
Binary for alpine Linux

### ISSUE THREAD

**Issue by WyseNynja** [grammarly/rocker-compose#56]
I tried to run rocker-compose from inside an alpine linux container with https://github.com/grammarly/rocker-compose/releases/download/0.1.6/rocker-compose_linux_amd64.tar.gz and it errd out the same way as https://github.com/docker/compose/issues/3465

Would it be possible to add build targets for alpine linux/musl libc along with the darwin and linux_amd64 builds?

**Comment by JonathonReinhart** [comment]
The problem, much like I described in docker/compose#3465 is that `rocker-compose` is a dynamically-linked executable built for GLIBC:

```
# file rocker-compose
rocker-compose: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=bd3de1dde03ea3f01181de681f2bfce5cd0a6d25, not stripped
```

This I am confused by however, because I thought all Go applications were statically-linked by default.

In this case, however, unlike docker/compose#3465, my hack *does* work:

```
# apk add libc6-compat
# ln -s /lib /lib64
# ./rocker-compose -v
rocker-compose version 0.1.6 - b1ddfe9 (master) 2016-09-01_14:15_GMT
```

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker-compose/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
